### ISSUE TITLE
请问能方便分享一下缺陷分类的数据集吗

### ISSUE THREAD

**Issue by lzh111222334** [YikiDragon/SolarPanelDefectDetect#1]
您好作者，很感谢您提供这么好的代码，方便分享下数据集吗

**Comment by YikiDragon** [comment]
你好，这个项目其实是我的《图像处理与理解》课程的大作业，数据集由授课老师张老师提供，我不确定这个数据集是否可以公开因此没有放在github上，如果你需要可以联系张老师，她的邮箱是jinxiazhang@seu.edu.cn，感谢你的来信！

**Comment by YikiDragon** [comment]
@lzh111222334 
你好，这个项目其实是我的《图像处理与理解》课程的大作业，数据集由授课老师张老师提供，我不确定这个数据集是否可以公开因此没有放在github上，如果你需要可以联系张老师，她的邮箱是jinxiazhang@seu.edu.cn，感谢你的来信！
